name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit tests & build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Installa dipendenze
        run: pnpm install --frozen-lockfile

      - name: Unit test
        run: pnpm test --run

      - name: Build
        run: pnpm build
